FROM ubuntu:12.04
            RUN dpkg-divert --local --rename --add /sbin/initctl
            RUN ln -sf /bin/true /sbin/initctl
            ENV DEBIAN_FRONTEND noninteractive
            RUN apt-get update
            RUN apt-get install -y sudo openssh-server curl lsb-release

          RUN if ! getent passwd kitchen; then useradd -d /home/kitchen -m -s /bin/bash kitchen; fi
          RUN echo kitchen:kitchen | chpasswd
          RUN echo 'kitchen ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
          RUN mkdir -p /etc/sudoers.d
          RUN echo 'kitchen ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/kitchen
          RUN chmod 0440 /etc/sudoers.d/kitchen
          RUN [ ! -d /home/kitchen/.ssh ] && mkdir /home/kitchen/.ssh
          RUN chown -R kitchen /home/kitchen/.ssh
          RUN chmod 0700 /home/kitchen/.ssh
          RUN echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjixpyX1nt9UeRnW84/J21GH1pLphjXyZEdMx0laZAvhYyPnY6WHjtT6mUPpKZGdEm3UapH0/9qJjSJPgu2/HMkHK+Qd+uHc16t9dZkZCjKLNO9dpi9QsrpRYLsBkkqkMzIH1OUnUKi/wW2rNVdHBGTqg0cp9+fCJM+aQrhXzfYE9WePaGD6E5/dGeadnHw7hB1ByM1O3nlfGTp+yDjljC1wh44Mc89B2hfCVKGTYKaInejTMSol/IjprpZefhLTUO+E1r5islaj3p1XGx4/HOqSacB/Wrs5o4/366k1yR8FOfymXE/2r8NpnSbFoYAlXJpObc80ecR1oEOSHBD7MJ kitchen_docker_key' >> /home/kitchen/.ssh/authorized_keys
          RUN chown kitchen /home/kitchen/.ssh/authorized_keys
          RUN chmod 0600 /home/kitchen/.ssh/authorized_keys

